# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iOSSharing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSSharing
  pod 'Alamofire', '5.1'

  target 'iOSSharingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSharingUITests' do
    # Pods for testing
  end

end
